### ISSUE TITLE
Xcode7.3 + pod version 1.0.0

### ISSUE THREAD

**Issue by iMaBiao** [kattrali/cocoapods-xcode-plugin#89]
Through Alcatraz installation

the error 
/usr/local/bin/pod install

/Library/Ruby/Site/2.0.0/rubygems.rb:250:in `find_spec_for_exe': can't find gem cocoapods (>= 0.a) (Gem::GemNotFoundException)
	from /Library/Ruby/Site/2.0.0/rubygems.rb:278:in `activate_bin_path'
	from /usr/local/bin/pod:22:in `<main>'

**Comment by XiangyangLi1314** [comment]
我也遇到了同样的问题，
